title: Create a navigation bar
hero_image: images/banner.png
description: Create a bar of navigation links
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Create a top navigation bar
